import slide4 from "../assets/slider/slide-4.jpg";
import image2 from "../assets/homPage/product-2.jpg";

export const eva_mats = {
   id: 1,
   pageName: "eva-mats",
   image: slide4,
   smallImg: image2,
   title: "EVA Коврики",
   text: "Для производства лучших ЭВА ковриков в стране, мы используем лучший ЭВА материал, лучшую фурнитуру, окантовку, липучку и самое главное лично снятые лекала с каждого авто. Гарантируем качество и даём гарантию на всё, что производим.",
   url: "/products/eva-mats",
   type: "romb",
   galleryImgs: [
      {
         id: 1,
         name: "base",
         imgUrl: "/products/Коврики/ЭВА_ромб/бежевый.png",
      },
      {
         id: 2,
         name: "border",
         imgUrl: "/products/Коврики/Кантики/ЭВА/бежевый.png",
      },
      {
         id: 3,
         name: "line",
         imgUrl: "/products/Коврики/Строчка_по_кантику/бежевый.png",
      },
   ],
   productTypes: [
      {
         stepText: "1 шаг: выберите тип материала",
         content: [
            {
               id: 1,
               img: "/products/Коврики/type-icon/mat-Ромб.png",
               type: "romb",
               text: "ЭВА ромб",
               base: "/products/Коврики/ЭВА_ромб/бежевый.png",
               border: "/products/Коврики/Кантики/ЭВА/бежевый.png",
               line: "/products/Коврики/Строчка_по_кантику/бежевый.png",
            },
            {
               id: 2,
               img: "/products/Коврики/type-icon/mat-Сота.png",
               type: "sota",
               text: "ЭВА сота",
               base: "/products/Коврики/ЭВА_сота/бежевый.png",
               border: "/products/Коврики/Кантики/ЭВА/бежевый.png",
               line: "/products/Коврики/Строчка_по_кантику/бежевый.png",
            },
         ],
      },
   ],
   options: [
      {
         stepText: "2 шаг: выберите цвет коврика",
         type: "romb",
         category: "base",
         content: [
            {
               id: 1,
               category: "base",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/ЭВА_ромб/бежевый.png",
            },
            {
               id: 2,
               category: "base",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/ЭВА_ромб/бордовый.png",
            },
            {
               id: 3,
               category: "base",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/ЭВА_ромб/коричневый.png",
            },
            {
               id: 4,
               category: "base",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/ЭВА_ромб/красный.png",
            },
            {
               id: 5,
               category: "base",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/ЭВА_ромб/серый.png",
            },
            {
               id: 6,
               category: "base",
               color: "blue",
               Text: "синий",
               imgUrl: "/products/Коврики/ЭВА_ромб/синий.png",
            },
            {
               id: 7,
               category: "base",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/ЭВА_ромб/черный.png",
            },
         ],
      },
      {
         stepText: "2 шаг: выберите цвет коврика",
         type: "sota",
         category: "base",
         content: [
            {
               id: 1,
               category: "base",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/ЭВА_сота/бежевый.png",
            },
            {
               id: 2,
               category: "base",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/ЭВА_сота/бордовый.png",
            },
            {
               id: 3,
               category: "base",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/ЭВА_сота/коричневый.png",
            },
            {
               id: 4,
               category: "base",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/ЭВА_сота/красный.png",
            },
            {
               id: 5,
               category: "base",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/ЭВА_сота/серый.png",
            },
            {
               id: 6,
               category: "base",
               color: "blue",
               Text: "синий",
               imgUrl: "/products/Коврики/ЭВА_сота/синий.png",
            },
            {
               id: 7,
               category: "base",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/ЭВА_сота/черный.png",
            },
         ],
      },
      {
         stepText: "3 шаг: выберите цвет окантовки",
         content: [
            {
               id: 1,
               category: "border",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/Кантики/ЭВА/бежевый.png",
            },
            {
               id: 2,
               category: "border",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/Кантики/ЭВА/бордовый.png",
            },
            {
               id: 3,
               category: "border",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/Кантики/ЭВА/коричневый.png",
            },
            {
               id: 4,
               category: "border",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/Кантики/ЭВА/красный.png",
            },
            {
               id: 5,
               category: "border",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/Кантики/ЭВА/серый.png",
            },
            {
               id: 6,
               category: "border",
               color: "blue",
               Text: "синий",
               imgUrl: "/products/Коврики/Кантики/ЭВА/синий.png",
            },
            {
               id: 7,
               category: "border",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/Кантики/ЭВА/черный.png",
            },
            {
               id: 8,
               category: "border",
               color: "green",
               Text: "зеленый",
               imgUrl: "/products/Коврики/Кантики/ЭВА/зеленый.png",
            },
            {
               id: 9,
               category: "border",
               color: "dark-blue",
               Text: "темно-синий",
               imgUrl: "/products/Коврики/Кантики/ЭВА/темно-синий.png",
            },
            {
               id: 10,
               category: "border",
               color: "light-blue",
               Text: "голубой",
               imgUrl: "/products/Коврики/Кантики/ЭВА/голубой.png",
            },
            {
               id: 11,
               category: "border",
               color: "silver",
               Text: "серебристый",
               imgUrl: "/products/Коврики/Кантики/ЭВА/серебристый.png",
            },
         ],
      },
      {
         stepText: "4 шаг: выберите цвет строчки по кантику",
         content: [
            {
               id: 1,
               category: "line",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/Строчка_по_кантику/бежевый.png",
            },
            {
               id: 2,
               category: "line",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/Строчка_по_кантику/бордовый.png",
            },
            {
               id: 3,
               category: "line",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/Строчка_по_кантику/коричневый.png",
            },
            {
               id: 4,
               category: "line",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/Строчка_по_кантику/красный.png",
            },
            {
               id: 5,
               category: "line",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/Строчка_по_кантику/серый.png",
            },
            {
               id: 6,
               category: "line",
               color: "blue",
               Text: "синий",
               imgUrl: "/products//Коврики/Строчка_по_кантику/синий.png",
            },
            {
               id: 7,
               category: "line",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/Строчка_по_кантику/черный.png",
            },
            {
               id: 8,
               category: "line",
               color: "orange",
               Text: "оранжевый",
               imgUrl: "/products/Коврики/Строчка_по_кантику/оранжевый.png",
            },
            {
               id: 9,
               category: "line",
               color: "dark-blue",
               Text: "темно-синий",
               imgUrl: "/products/Коврики/Строчка_по_кантику/темно-синий.png",
            },
            {
               id: 10,
               category: "line",
               color: "white",
               Text: "белый",
               imgUrl: "/products/Коврики/Строчка_по_кантику/белый.png",
            },
         ],
      },
   ],
};
