import slide4 from "../assets/slider/slide-4.jpg";
import image1 from "../assets/homPage/product-1.jpg";

export const leather_mats = {
   id: 2,
   pageName: "leather-mats",
   image: slide4,
   smallImg: image1,
   title: "Коврики из эко кожи",
   text: "Это так называемый премиум сегмент нашего производства. Как всегда лично снятые лекала с каждого авто, проверенные годами материалы, ровные строчки и трепетное отношение к каждому комплекту. Наши коврики из эко кожи преоброзят даже самый дорогой и изысканный салон вашего автомобиля.",
   url: "/products/leather-mats",
   type: "square",
   galleryImgs: [
      {
         id: 1,
         name: "base",
         imgUrl: "/products/Коврики/Кожа/бежевый.png",
      },
      {
         id: 2,
         name: "border",
         imgUrl: "/products/Коврики/Кантики/кожаный/бежевый.png",
      },
      {
         id: 3,
         name: "line",
         imgUrl: "/products/Коврики/Узоры/Квадрат/бежевый.png",
      },
   ],
   productTypes: [
      {
         stepText: "1 шаг: выберите тип узора",
         content: [
            {
               id: 1,
               img: "/products/Кофры/type-icon/квадратный.png",
               type: "square",
               text: "Квадрат",
               base: "/products/Коврики/Кожа/бежевый.png",
               border: "/products/Коврики/Кантики/кожаный/бежевый.png",
               line: "/products/Коврики/Узоры/Квадрат/бежевый.png",
            },
            {
               id: 2,
               img: "/products/Кофры/type-icon/линия.png",
               type: "strip",
               text: "Полоса",
               base: "/products/Коврики/Кожа/бежевый.png",
               border: "/products/Коврики/Кантики/кожаный/бежевый.png",
               line: "/products/Коврики/Узоры/Полоса/бежевый.png",
            },
            {
               id: 3,
               img: "/products/Кофры/type-icon/линия.png",
               type: "double-strip",
               text: "Полоса двойная",
               base: "/products/Коврики/Кожа/бежевый.png",
               border: "/products/Коврики/Кантики/кожаный/бежевый.png",
               line: "/products/Коврики/Узоры/Полоса двойная/бежевый.png",
            },
            {
               id: 4,
               img: "/products/Кофры/type-icon/ромб.png",
               type: "romb",
               text: "Ромб",
               base: "/products/Коврики/Кожа/бежевый.png",
               border: "/products/Коврики/Кантики/кожаный/бежевый.png",
               line: "/products/Коврики/Узоры/Ромб/бежевый.png",
            },
            {
               id: 5,
               img: "/products/Кофры/type-icon/ромб.png",
               type: "double-romb",
               text: "Ромб двойной",
               base: "/products/Коврики/Кожа/бежевый.png",
               border: "/products/Коврики/Кантики/кожаный/бежевый.png",
               line: "/products/Коврики/Узоры/Ромб двойной/бежевый.png",
            },
            {
               id: 6,
               img: "/products/Кофры/type-icon/линия.png",
               type: "sota",
               text: "Сота",
               base: "/products/Коврики/Кожа/бежевый.png",
               border: "/products/Коврики/Кантики/кожаный/бежевый.png",
               line: "/products/Коврики/Узоры/Сота/бежевый.png",
            },
         ],
      },
   ],
   options: [
      {
         stepText: "2 шаг: выберите цвет узора",
         type: "square",
         content: [
            {
               id: 1,
               category: "line",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/Узоры/Квадрат/бежевый.png",
            },
            {
               id: 2,
               category: "line",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/Узоры/Квадрат/бордовый.png",
            },
            {
               id: 3,
               category: "line",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/Узоры/Квадрат/коричневый.png",
            },
            {
               id: 4,
               category: "line",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/Узоры/Квадрат/красный.png",
            },
            {
               id: 5,
               category: "line",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/Узоры/Квадрат/серый.png",
            },
            {
               id: 6,
               category: "line",
               color: "blue",
               Text: "синий",
               imgUrl: "/products/Коврики/Узоры/Квадрат/синий.png",
            },
            {
               id: 7,
               category: "line",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/Узоры/Квадрат/черный.png",
            },
            {
               id: 8,
               category: "line",
               color: "orange",
               Text: "оранжевый",
               imgUrl: "/products/Коврики/Узоры/Квадрат/оранжевый.png",
            },
            {
               id: 9,
               category: "line",
               color: "dark-blue",
               Text: "темно-синий",
               imgUrl: "/products/Коврики/Узоры/Квадрат/темно-синий.png",
            },
            {
               id: 10,
               category: "line",
               color: "white",
               Text: "белый",
               imgUrl: "/products/Коврики/Узоры/Квадрат/белый.png",
            },
         ],
      },
      {
         stepText: "2 шаг: выберите цвет узора",
         type: "strip",
         content: [
            {
               id: 1,
               category: "line",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/Узоры/Полоса/бежевый.png",
            },
            {
               id: 2,
               category: "line",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/Узоры/Полоса/бордовый.png",
            },
            {
               id: 3,
               category: "line",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/Узоры/Полоса/коричневый.png",
            },
            {
               id: 4,
               category: "line",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/Узоры/Полоса/красный.png",
            },
            {
               id: 5,
               category: "line",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/Узоры/Полоса/серый.png",
            },
            {
               id: 6,
               category: "line",
               color: "blue",
               Text: "синий",
               imgUrl: "/products/Коврики/Узоры/Полоса/синий.png",
            },
            {
               id: 7,
               category: "line",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/Узоры/Полоса/черный.png",
            },
            {
               id: 8,
               category: "line",
               color: "orange",
               Text: "оранжевый",
               imgUrl: "/products/Коврики/Узоры/Полоса/оранжевый.png",
            },
            {
               id: 9,
               category: "line",
               color: "dark-blue",
               Text: "темно-синий",
               imgUrl: "/products/Коврики/Узоры/Полоса/темно-синий.png",
            },
            {
               id: 10,
               category: "line",
               color: "white",
               Text: "белый",
               imgUrl: "/products/Коврики/Узоры/Полоса/белый.png",
            },
         ],
      },
      {
         stepText: "2 шаг: выберите цвет узора",
         type: "double-strip",
         content: [
            {
               id: 1,
               category: "line",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/Узоры/Полоса двойная/бежевый.png",
            },
            {
               id: 2,
               category: "line",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/Узоры/Полоса двойная/бордовый.png",
            },
            {
               id: 3,
               category: "line",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/Узоры/Полоса двойная/коричневый.png",
            },
            {
               id: 4,
               category: "line",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/Узоры/Полоса двойная/красный.png",
            },
            {
               id: 5,
               category: "line",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/Узоры/Полоса двойная/серый.png",
            },
            {
               id: 6,
               category: "line",
               color: "blue",
               Text: "синий",
               imgUrl: "/products/Коврики/Узоры/Полоса двойная/синий.png",
            },
            {
               id: 7,
               category: "line",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/Узоры/Полоса двойная/черный.png",
            },
            {
               id: 8,
               category: "line",
               color: "orange",
               Text: "оранжевый",
               imgUrl: "/products/Коврики/Узоры/Полоса двойная/оранжевый.png",
            },
            {
               id: 9,
               category: "line",
               color: "dark-blue",
               Text: "темно-синий",
               imgUrl: "/products/Коврики/Узоры/Полоса двойная/темно-синий.png",
            },
            {
               id: 10,
               category: "line",
               color: "white",
               Text: "белый",
               imgUrl: "/products/Коврики/Узоры/Полоса двойная/белый.png",
            },
         ],
      },
      {
         stepText: "2 шаг: выберите цвет узора",
         type: "romb",
         content: [
            {
               id: 1,
               category: "line",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/Узоры/Ромб/бежевый.png",
            },
            {
               id: 2,
               category: "line",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/Узоры/Ромб/бордовый.png",
            },
            {
               id: 3,
               category: "line",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/Узоры/Ромб/коричневый.png",
            },
            {
               id: 4,
               category: "line",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/Узоры/Ромб/красный.png",
            },
            {
               id: 5,
               category: "line",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/Узоры/Ромб/серый.png",
            },
            {
               id: 6,
               category: "line",
               color: "blue",
               Text: "синий",
               imgUrl: "/products/Коврики/Узоры/Ромб/синий.png",
            },
            {
               id: 7,
               category: "line",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/Узоры/Ромб/черный.png",
            },
            {
               id: 8,
               category: "line",
               color: "orange",
               Text: "оранжевый",
               imgUrl: "/products/Коврики/Узоры/Ромб/оранжевый.png",
            },
            {
               id: 9,
               category: "line",
               color: "dark-blue",
               Text: "темно-синий",
               imgUrl: "/products/Коврики/Узоры/Ромб/темно-синий.png",
            },
            {
               id: 10,
               category: "line",
               color: "white",
               Text: "белый",
               imgUrl: "/products/Коврики/Узоры/Ромб/белый.png",
            },
         ],
      },
      {
         stepText: "2 шаг: выберите цвет узора",
         type: "double-romb",
         content: [
            {
               id: 1,
               category: "line",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/Узоры/Ромб двойной/бежевый.png",
            },
            {
               id: 2,
               category: "line",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/Узоры/Ромб двойной/бордовый.png",
            },
            {
               id: 3,
               category: "line",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/Узоры/Ромб двойной/коричневый.png",
            },
            {
               id: 4,
               category: "line",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/Узоры/Ромб двойной/красный.png",
            },
            {
               id: 5,
               category: "line",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/Узоры/Ромб двойной/серый.png",
            },
            {
               id: 6,
               category: "line",
               color: "blue",
               Text: "синий",
               imgUrl: "/products/Коврики/Узоры/Ромб двойной/синий.png",
            },
            {
               id: 7,
               category: "line",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/Узоры/Ромб двойной/черный.png",
            },
            {
               id: 8,
               category: "line",
               color: "orange",
               Text: "оранжевый",
               imgUrl: "/products/Коврики/Узоры/Ромб двойной/оранжевый.png",
            },
            {
               id: 9,
               category: "line",
               color: "dark-blue",
               Text: "темно-синий",
               imgUrl: "/products/Коврики/Узоры/Ромб двойной/темно-синий.png",
            },
            {
               id: 10,
               category: "line",
               color: "white",
               Text: "белый",
               imgUrl: "/products/Коврики/Узоры/Ромб двойной/белый.png",
            },
         ],
      },
      {
         stepText: "2 шаг: выберите цвет узора",
         type: "sota",
         content: [
            {
               id: 1,
               category: "line",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/Узоры/Сота/бежевый.png",
            },
            {
               id: 2,
               category: "line",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/Узоры/Сота/бордовый.png",
            },
            {
               id: 3,
               category: "line",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/Узоры/Сота/коричневый.png",
            },
            {
               id: 4,
               category: "line",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/Узоры/Сота/красный.png",
            },
            {
               id: 5,
               category: "line",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/Узоры/Сота/серый.png",
            },
            {
               id: 6,
               category: "line",
               color: "blue",
               Text: "синий",
               imgUrl: "/products/Коврики/Узоры/Сота/синий.png",
            },
            {
               id: 7,
               category: "line",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/Узоры/Сота/черный.png",
            },
            {
               id: 8,
               category: "line",
               color: "orange",
               Text: "оранжевый",
               imgUrl: "/products/Коврики/Узоры/Сота/оранжевый.png",
            },
            {
               id: 9,
               category: "line",
               color: "dark-blue",
               Text: "темно-синий",
               imgUrl: "/products/Коврики/Узоры/Сота/темно-синий.png",
            },
            {
               id: 10,
               category: "line",
               color: "white",
               Text: "белый",
               imgUrl: "/products/Коврики/Узоры/Сота/белый.png",
            },
         ],
      },
      {
         stepText: "3 шаг: выберите цвет коврика",
         content: [
            {
               id: 1,
               category: "base",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/Кожа/бежевый.png",
            },
            {
               id: 2,
               category: "base",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/Кожа/бордовый.png",
            },
            {
               id: 3,
               category: "base",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/Кожа/коричневый.png",
            },
            {
               id: 4,
               category: "base",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/Кожа/красный.png",
            },
            {
               id: 5,
               category: "base",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/Кожа/серый.png",
            },
            {
               id: 6,
               category: "base",
               color: "blue",
               Text: "синий",
               imgUrl: "/products/Коврики/Кожа/синий.png",
            },
            {
               id: 7,
               category: "base",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/Кожа/черный.png",
            },
            {
               id: 8,
               category: "base",
               color: "orange",
               Text: "оранжевый",
               imgUrl: "/products/Коврики/Кожа/оранжевый.png",
            },
            {
               id: 9,
               category: "base",
               color: "dark-blue",
               Text: "темно-синий",
               imgUrl: "/products/Коврики/Кожа/темно-синий.png",
            },
            {
               id: 10,
               category: "base",
               color: "white",
               Text: "белый",
               imgUrl: "/products/Коврики/Кожа/Белыый.png",
            },
         ],
      },
      {
         stepText: "4 шаг: выберите цвет окантовки",
         content: [
            {
               id: 1,
               category: "border",
               color: "beige",
               Text: "бежевый",
               imgUrl: "/products/Коврики/Кантики/кожаный/бежевый.png",
            },
            {
               id: 2,
               category: "border",
               color: "burgundy",
               Text: "бордовый",
               imgUrl: "/products/Коврики/Кантики/кожаный/бордовый.png",
            },
            {
               id: 3,
               category: "border",
               color: "brown",
               Text: "коричневый",
               imgUrl: "/products/Коврики/Кантики/кожаный/коричневый.png",
            },
            {
               id: 4,
               category: "border",
               color: "red",
               Text: "красный",
               imgUrl: "/products/Коврики/Кантики/кожаный/красный.png",
            },
            {
               id: 5,
               category: "border",
               color: "gray",
               Text: "серый",
               imgUrl: "/products/Коврики/Кантики/кожаный/серый.png",
            },
            {
               id: 6,
               category: "border",
               color: "blue",
               Text: "синий",
               imgUrl: "/products/Коврики/Кантики/кожаный/синий.png",
            },
            {
               id: 7,
               category: "border",
               color: "black",
               Text: "черный",
               imgUrl: "/products/Коврики/Кантики/кожаный/черный.png",
            },

            {
               id: 8,
               category: "border",
               color: "orange",
               Text: "оранжевый",
               imgUrl: "/products/Коврики/Кантики/кожаный/оранжевый.png",
            },
            {
               id: 9,
               category: "border",
               color: "dark-blue",
               Text: "темно-синий",
               imgUrl: "/products/Коврики/Кантики/кожаный/темно-синий.png",
            },
            {
               id: 10,
               category: "border",
               color: "white",
               Text: "белый",
               imgUrl: "/products/Коврики/Кантики/кожаный/белый.png",
            },
         ],
      },
   ],
};
